name: Weekly release

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # https://crontab.guru/#0_0_*_*_1
    # “At 00:00 on Monday.”
    - cron: '0 0 * * 1'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out to the repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Make data from commits
      run: |
        python make_data_from_commits.py
        ls -lah
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        files: |
          *.zip
    - name: Create repository dispatch event
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        gh api repos/eozer/krdae-history/dispatches \
          --raw-field event_type=krdae-data-event
